name: Action Test
on: workflow_dispatch

jobs:

  #====== Test ======#
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:

      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Run custom action
      - name: Run custom action 
        uses: ./src/DockerContainer
        id: hello
        with:
          who-to-greet: 'GitHub'
