name: Deploy to GitHub Pages
env:
  PUBLISH_DIR: src/Blazor.Client.HelloWorld/bin/Release/net8.0/publish/wwwroot

# Controls when the action will run
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Publish app
      run: dotnet publish ./src/Blazor.Client.HelloWorld/Blazor.Client.HelloWorld.csproj -c Release

    - name: Rewrite base href
      uses: SteveSandersonMS/ghaction-rewrite-base-href@v1
      with:
        html_path: ${{ env.PUBLISH_DIR }}/index.html
        base_href: /BlazorOnGitHubPages/

    - name: GitHub Pages
      if: success()
      uses: JamesIves/github-pages-deploy-action@4.1.5
      with:
        branch: gh-pages
        folder: ${{ env.PUBLISH_DIR }}
        token: ${{ secrets.GITHUB_TOKEN }}
