name: GitHub Pages Deploy
on:
  workflow_dispatch:

env:
  # Define the output directory explicitly
  PUBLISH_DIR: src/Blazor.WebAssembly/bin/GitHubPages/net8.0/publish/wwwroot

jobs:

  #====== Build and Publish ======#
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      # Step 3: Publish App
      - name: Publish app
        run: |
          dotnet publish ./src/Blazor.WebAssembly/Blazor.WebAssembly.csproj -c GitHubPages -o src/Blazor.WebAssembly/bin/GitHubPages/net8.0/publish
        env:
          DOTNET_ROOT: /usr/share/dotnet

      # Step 4: List published files for debugging
      - name: List published files
        run: ls -R ${{ env.PUBLISH_DIR }}
        if: always()

      # Step 5: Upload Pages Artifact
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ env.PUBLISH_DIR }}

  #====== Deploy to GitHub Pages ======#
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      # Step 1: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
