name: GitHub Pages Deploy
on: workflow_dispatch
env:
  PUBLISH_DIR: src/Blazor.WebAssembly/bin/GitHubPages/net8.0/publish/wwwroot

jobs:

  #====== Build and publish ======#
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:

      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup .NET
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
    
      # Step 3: Publish App
      - name: Publish app
        run: dotnet publish ./src/Blazor.WebAssembly/Blazor.WebAssembly.csproj -c GitHubPages

      # Step 3.5: List published files for debugging
      - name: List published files
        run: ls -R ${{ env.PUBLISH_DIR }}
        if: always()
    
      # Step 4: Archive production artifacts
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: published-app
          path: ${{ env.PUBLISH_DIR }}
          if-no-files-found: warn
          compression-level: 6
          overwrite: false
          include-hidden-files: false
        env:
          DOTNET_ROOT: /usr/share/dotnet


  #====== Deploy to GitHub Pages ======#
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:

      # Step 1: Download artifact
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: published-app
          path: ./wwwroot

      # Step 2: Publish to GitHub Pages
      - name: Publish
        uses: crazy-max/ghaction-github-pages@v4
        with:
          target_branch: gh-pages
          build_dir: ./wwwroot
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
