name: Create Azure Static Web Apps
on: workflow_dispatch

jobs:

  #====== Build and deploy ======#
  build_and_deploy:
    name: "Build and Deploy"
    runs-on: ubuntu-latest

    steps:

    # Checkout repository
    - name: Checkout repository
      uses: actions/checkout@v4

    # Login to Azure
    - name: Login to Azure
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy ARM template
    - name: Deploy ARM Template
      uses: azure/arm-deploy@v2
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.HELLOWORLD_RESOURCE_GROUP_NAME }}
        template: ./infra/azuredeploy.json
        parameters: ./infra/azuredeploy.parameters.json
        deploymentMode: Incremental

    # Logout of Azure
    - name: Logout of Azure
      run: |
        az logout

